'use client';

import React from 'react';
import { motion } from 'framer-motion';
import { Sparkles, TrendingUp, Clock, Hash } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';

export function AIRecommendation() {
  const recommendation =
    'Post your Bali travel reel today at 7:30 PM for maximum engagement.';
  const expectedEngagement = 18;
  const hashtags = ['#travelreels', '#balivibes', '#explorebali'];

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.4, ease: 'easeOut' }}
    >
      <Card className="h-full min-h-[420px] flex flex-col border-border bg-card shadow-sm hover:shadow-lg hover:-translate-y-1 transition-all duration-300">
        <CardHeader>
          <div className="flex items-center gap-2 mb-4">
            <Sparkles className="w-5 h-5 text-green-400" />
            <h3 className="font-semibold text-lg text-foreground">AI Recommendation</h3>
          </div>
          <p className="text-sm text-muted-foreground">Insights generated by Orin AI</p>
        </CardHeader>

        <CardContent className="space-y-4">
          {/* Recommendation Block */}
          <div className="p-4 rounded-lg bg-primary/5 border border-primary/20">
            <p className="text-sm text-foreground leading-relaxed">
              {recommendation}
            </p>
          </div>

          {/* Expected Engagement */}
          <div>
            <div className="flex items-center justify-between mb-2">
              <div className="flex items-center gap-2">
                <TrendingUp className="w-4 h-4 text-primary" />
                <span className="text-sm text-muted-foreground">Expected Engagement</span>
              </div>
              <span className="text-sm font-semibold text-foreground">+{expectedEngagement}%</span>
            </div>
            <div className="w-full h-2 rounded-full bg-secondary overflow-hidden">
              <motion.div
                className="h-full bg-gradient-to-r from-primary to-primary/70"
                initial={{ width: 0 }}
                animate={{ width: `${expectedEngagement}%` }}
                transition={{ delay: 0.2, duration: 0.6, ease: 'easeOut' }}
              />
            </div>
          </div>

          {/* Suggested Time */}
          <div className="flex items-center gap-2">
            <Clock className="w-4 h-4 text-primary" />
            <span className="text-sm text-muted-foreground">Recommended Time:</span>
            <span className="text-sm font-semibold text-foreground">Today at 7:30 PM</span>
          </div>

          {/* Hashtags */}
          <div className="space-y-2">
            <div className="flex items-center gap-2">
              <Hash className="w-4 h-4 text-primary" />
              <span className="text-sm text-muted-foreground">Suggested Hashtags</span>
            </div>
            <div className="flex flex-wrap gap-2">
              {hashtags.map((tag) => (
                <span
                  key={tag}
                  className="inline-block px-2.5 py-1 rounded-full bg-secondary text-foreground text-xs"
                >
                  {tag}
                </span>
              ))}
            </div>
          </div>

          {/* Additional Insight */}
          <div className="mt-4 p-3 rounded-lg bg-muted/40 border border-border">
            <p className="text-sm text-muted-foreground">
              AI predicts this post will reach{' '}
              <span className="text-green-400 font-semibold">2.4x more audience</span>{' '}
              compared to your average posts.
            </p>
          </div>

          {/* Apply Button */}
          <Button className="w-full bg-primary hover:bg-primary/90 text-primary-foreground mt-2">
            Apply Recommendation
          </Button>
        </CardContent>
      </Card>
    </motion.div>
  );
}
